# Custom Language File for Launcher Customizer

[ejs.app]
title = "Wicked Launcher"

[ejs.landing]
mediaLinkURL = "#"
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "WickedGang Launcher에 자리하게"
welcomeDescription = "한번 만들어봣네"
welcomeDescCTA = "자리해라"
